
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ID INTLIT\n    Program : ID ID '(' ')' '{' Declarations Statements '}'\n    \n    Declarations : Declarations Declaration\n                 | Declaration\n    \n    Declaration : ID ID ';'\n    \n    Statements : Statements Statement\n               | Statement\n    \n    Statement : Assignment\n    \n    Assignment : ID '=' Expression ';'\n    \n    Expression : Expression '+' Term\n               | Term\n    \n    Term : Term '*' Factor\n         | Factor\n    \n    Factor : INTLIT \n            | '(' Expression ')'\n    "
    
_lr_action_items = {'ID':([0,2,6,7,8,9,11,12,13,14,15,16,20,26,],[2,3,7,10,11,-3,10,18,-2,-6,-7,-4,-5,-8,]),'$end':([1,19,],[0,-1,]),'(':([3,17,25,27,28,],[4,25,25,25,25,]),')':([4,22,23,24,29,30,31,32,],[5,-10,-12,-13,32,-9,-11,-14,]),'{':([5,],[6,]),';':([10,21,22,23,24,30,31,32,],[16,26,-10,-12,-13,-9,-11,-14,]),'=':([11,18,],[17,17,]),'}':([12,14,15,20,26,],[19,-6,-7,-5,-8,]),'INTLIT':([17,25,27,28,],[24,24,24,24,]),'+':([21,22,23,24,29,30,31,32,],[27,-10,-12,-13,27,-9,-11,-14,]),'*':([22,23,24,30,31,32,],[28,-12,-13,28,-11,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Program':([0,],[1,]),'Declarations':([6,],[8,]),'Declaration':([6,8,],[9,13,]),'Statements':([8,],[12,]),'Statement':([8,12,],[14,20,]),'Assignment':([8,12,],[15,15,]),'Expression':([17,25,],[21,29,]),'Term':([17,25,27,],[22,22,30,]),'Factor':([17,25,27,28,],[23,23,23,31,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Program","S'",1,None,None,None),
  ('Program -> ID ID ( ) { Declarations Statements }','Program',8,'p_Program','analisis.py',32),
  ('Declarations -> Declarations Declaration','Declarations',2,'p_Declarations','analisis.py',38),
  ('Declarations -> Declaration','Declarations',1,'p_Declarations','analisis.py',39),
  ('Declaration -> ID ID ;','Declaration',3,'p_Declaration','analisis.py',49),
  ('Statements -> Statements Statement','Statements',2,'p_Statements','analisis.py',55),
  ('Statements -> Statement','Statements',1,'p_Statements','analisis.py',56),
  ('Statement -> Assignment','Statement',1,'p_Statement','analisis.py',65),
  ('Assignment -> ID = Expression ;','Assignment',4,'p_Assignment','analisis.py',71),
  ('Expression -> Expression + Term','Expression',3,'p_Expression','analisis.py',77),
  ('Expression -> Term','Expression',1,'p_Expression','analisis.py',78),
  ('Term -> Term * Factor','Term',3,'p_Term','analisis.py',88),
  ('Term -> Factor','Term',1,'p_Term','analisis.py',89),
  ('Factor -> INTLIT','Factor',1,'p_Factor','analisis.py',98),
  ('Factor -> ( Expression )','Factor',3,'p_Factor','analisis.py',99),
]
